# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestProject
  rn_path = '../node_modules/react-native'
    rn_maps_path = '../node_modules/react-native-maps'

    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
    ]

    pod 'react-native-maps', path: rn_maps_path
    pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
    pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
    pod 'GoogleMaps'  # Remove this line if you don't want to support Google Maps on iOS
    pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support Google Maps on iOS
    pod 'Google-Maps-iOS-Utils', :git => 'https://github.com/pjamrozowicz/google-maps-ios-utils.git'
    # pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  # pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'FacebookSDK','~> 4.38.0'
  pod 'FBSDKShareKit','~> 4.38.0'
  pod 'FBSDKLoginKit','~> 4.38.0'

  
  pod 'Firebase/Core','~> 5.15.0'
   pod 'Firebase/Messaging'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
